// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://autgttuxjboppqjmpkfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1dGd0dHV4amJvcHBxam1wa2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI3NTAzNDQsImV4cCI6MjA5ODMyNjM0NH0.PcE0YfDa-zthGjtCjUEgCS--U7I_gcxZvNgHq-0bT_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);